### ISSUE TITLE
You don't need to end every line in python with ; jesus christ

### ISSUE THREAD

**Issue by Martmists-GH** [XNBlank/sudoBot#6]

**Comment by Pheonix5555** [comment]
Bump

**Comment by designategold7** [comment]
bump

**Comment by XNBlank** [comment]
It's a habit of mine from other programming languages. Shoot me.
https://github.com/XNBlank/sudoBot/commit/e8dc6b7ddab110d41bc828b79771930708f4924d

**Comment by designategold7** [comment]
"shoot me." consider it done

**Comment by XNBlank** [comment]
@voqz I never said I wouldn't do it. I said it's a habit of mine and that probably wont change in the future.
My response seemed a bit rude however, so my apologies. Wasn't having a good day.
